"""added a column to hold user id in the comment table
Revision ID: 7222d43c108f
Revises: b717b270c9cf
Create Date: 2018-09-10 12:53:47.570701
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7222d43c108f'
down_revision = 'b717b270c9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
