
"""class UpdateProfile(FlaskForm):
Revision ID: 91418a3b5b22
Revises: 1978dfb2f581
Create Date: 2018-09-08 20:27:12.245234
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91418a3b5b22'
down_revision = '1978dfb2f581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###